# Kyouki
Chapter - 1: Confession
When life was life like- i can say beautiful. i was a kid. playing with my little life. Once upon a day the most terrible day of my life has came. the day like sahir,fahim,borno and etc. started calling me "Notun Jamai" like that time ig i felt it is a lie for the first time in my entire life. but out of nowhere i kinda felt glad, happy, a wierdness, somewhere proud.....but the real thing is i didnt even knew the reason what tf is going on. One the Sahir told me "konda" point at the bench whe "Tanjina" and "naima" was sitting . I was like hea oita pointing at "Her". They waas like "Hoo, polay thik ta e dhorse". Then i kinda started getting things...then they explained the told me that "She has a crush on me". i was like " what??" (inside me was: hey i look bad as shit,ugly,wierd. what made her fall for me. For the first time i get to know that "Love" )
Chapter - 2: Encounter 
From that day i was kind of changed. cuz yk that. soo well. one day for the first time she texted me....i was surprised not shocked.and here the play goes-------She first asked me if i had a crush or not , to be honest, i was a avrage lonly boy jar "Mahim" chara ar kew cilo naa.........
Chapter - 2:(Interlude): The Breakdown starts
"Mahim was not a boy, not a kid, not a friend, HE WAS A FUCKING BROTHER OF MINE. When people hated me he was standing beside me.When i felt alone, he sat beside me , he kept silent but is was - it was really a lot A LOT for Me . When i had 10 tk i used to eat 5 i gave bro 5. another time bro bring 100 tk i took 50 bro spended 50 (equally).Not gonna lie i also did the same...... I loved him. My brother the man i used to call "Mahim" .
Chapter - 2:(Continues): Encounter
.......I wasn't that interested in girls of even human beings. Life for no reason she killed me---------
